### ISSUE TITLE
File `cnnModel/poseAnalysis.py` is missing

### ISSUE THREAD

**Issue by ZC119** [stephen-w-bailey/fast-n-deep-faces#1]
Hi,

I couldn't find `poseAnalysis.py` in folder `cnnModel` when trainning refinement model. However, I can still train refinement model without this command: 

`python3 cnnModel/poseAnalysis.py --configFile models/refine_model_leaky.yaml --outputFile models/cache_refined.pkl`

I was wondering what this `poseAnalysis.py` does. 

Thanks. :)

**Comment by stephen-w-bailey** [comment]
Thanks for pointing out the missing file.  That is a typo, and the correct file should be `cnnModel/computeParameterMasks.py`, which will determine the control influences for the refinement model, similar to what was done for the coarse model.

The readme file has been updated with this correction.
