### ISSUE TITLE
Why is the  implementation of function `rigidRegister` so different from the paer `Least-Squares Rigid Motion Using SVD` ?

### ISSUE THREAD

**Issue by MengHao666** [stephen-w-bailey/fast-n-deep-faces#14]
Hi,

thanks for your great work. I am currently read your paper and code of `Fast And Deep Facial Deformations`. And I feel ver confused about the implementation of  function `rigidRegister`. It seems very different from the note [Least-Squares Rigid Motion Using SVD](https://igl.ethz.ch/projects/ARAP/svd_rot.pdf).

Are these two implementations equal mathematics? Or is there any difference in quality or speed between solutions?

**Comment by dalton-omens** [comment]
These two implementations are mathematically equivalent when det(R) >= 0. This implementation doesn't handle the case where det(R) < 0 by flipping the sign of the last column of V.

Note that the rigidRegister() expression  (U S^-1 U^T U S V^T)^T  = V U^T (the equivalent expression in the note you linked)

**Comment by MengHao666** [comment]
> These two implementations are mathematically equivalent when det(R) >= 0. This implementation doesn't handle the case where det(R) < 0 by flipping the sign of the last column of V.
> 
> Note that the rigidRegister() expression (U S^-1 U^T U S V^T)^T = V U^T (the equivalent expression in the note you linked)

Thanks for your kind reply. It seems the value of `det(R)` could only be `+1` or `-1` as expained in the [note](https://igl.ethz.ch/projects/ARAP/svd_rot.pdf). Now that, as you said, these two implementations are equal in mathematics. why don't you just use ` R = U.dot(V).T  ` as [here](https://github.com/dalton-omens/SSDR/blob/71ef96eabafbfe88d19955d47218a1557a396b31/SSDR.py#L32) ? Is there any reason for quality or peformance. It seems the latter is simpler and clearer.

**Comment by dalton-omens** [comment]
Since they are equivalent, you can use either. I don't remember the reasoning but it wasn't something we thought too hard about. Probably U.dot(V).T is slightly faster (just a guess).

**Comment by MengHao666** [comment]
> Since they are equivalent, you can use either. I don't remember the reasoning but it wasn't something we thought too hard about. Probably U.dot(V).T is slightly faster (just a guess).

Got it! Thanks for your patience and explainations!
